### ISSUE TITLE
Scope of this library

### ISSUE THREAD

**Issue by dbartholomae** [open-constructs/aws-cdk-library#14]
What kind of constructs do we want to have in here? What's the main focus that we actively try to get in, which ones do we accept and maintain but would not proactively add ourselves?

Ideally we can first align on the rough direction here, and I'm happy to create an ADR out of this. My impression is that there is overall alignment to focus on "L2s that would have been accepted in to aws-cdk in the past, but now no longer will", but there are edge cases which are not super clear from this definition. Also, we did discuss to potentially have L3 constructs in here as well.

We have some implicit assumptions around this in [our ADR to folder structure](https://github.com/open-constructs/aws-cdk-library/blob/main/decisions/ADR-01-Repo-Structure.md) which mentions L3 constructs like `static-website` and helpers like `typescript-asset`, but we never explicitly discussed whether these should actually part of this library.

A concrete example for this is the discussion around in-project lambdas or TypeScript assets in #8. We also started part of this discussion in #13.

**Comment by go-to-k** [comment]
[Our contributing guide](https://github.com/open-constructs/aws-cdk-library/blob/main/CONTRIBUTING.md#construct-design) says that `Focus on only accepting L2 constructs to start. L3 constructs will come later as the library matures.`. I take it that L2, which is not in the aws-cdk now, is accepted as a priority, and L3 is also accepted, but with a lower priority. (Or it may have the potential to leave all L3s alone now.)

It would be good to discuss edge cases on a case-by-case basis. However, I personally feel that the edge cases, which are difficult to determine, would be treated the same as L3. Probably because they are less likely to be accepted by the aws-cdk than L2.

**Comment by hoegertn** [comment]
My vision for this library definitely is more L3s as these will not be added to CDK core. But for the start I see that adding L2 is a priority as there are many out there that could look for a place to live.

So IMHO it is L2s first but definitely also L3s in the (near) future

**Comment by dbartholomae** [comment]
Based on the discussion here and a related discussion in Slack between maintainers, I would summarise our stance as:
We currently prioritise L2s, but topics that are not clearly in focus can be picked up by maintainers as long as no other topic that clearly _is_ in focus demands their attention.
